shallow_clone: true
skip_branch_with_pr: true
build_script:
    - cmd: pip install jsonschema==2.6.0
test_script:
    - cmd: jsonschema -i just-install.json just-install-schema.json
    - cmd: msiexec /q /i https://just-install.github.io/stable/just-install.msi
    - cmd: just-install audit
